library("dplyr")
library("DBI")
library("phytools")
library("tidyr")
library("data.table")
library("tibble")
library("raster")
library("sp")
library("ggplot2")



base<-"/home/huijieqiao/git/ees_3d_data/niche_conservatism"
db_base<-"/home/huijieqiao/git/ees_3d_data/SMART_SPECIES"
base2<-"/media/huijieqiao/Butterfly/SMART_SPECIES"


#the rda file was generated by global_id_lonlat.r
mask_df<-readRDS(sprintf("%s/Data/ENV/mask_df.rda", base))

simulations<-NULL
for (i in c(1,2,7)){
#for (i in c(7)){
  print(i)
  mydb <- dbConnect(RSQLite::SQLite(), sprintf("%s/conf_%s.sqlite", db_base, i))  
  simulation<-dbReadTable(mydb, "simulations")
  dbDisconnect(mydb) 
  if (is.null(simulations)){
    simulations<-simulation
  }else{
    simulations<-bind_rows(simulation, simulations)
  }
}
handle_label<-function(label){
  if (length(label)==4){
    label<-c(label, label[4])
  }
  label[c(1,4,5)]
}
simulations<-simulations %>% filter(nb!="BROAD")
simulations<-simulations %>% filter(is_run==1)

stat<-readRDS(sprintf("%s/Data/stat.rda", base))
stat%>%dplyr::filter(between(N_SPECIATION, 100, 200)&between(N_EXTINCTION, 10, 20) )
example<-stat%>%dplyr::filter((SEED_ID==6225)&(DA=="GOOD")&(NB=="MODERATE"))
simulation<-simulations%>%dplyr::filter((global_id==6225)&(da=="GOOD")&(nb=="MODERATE"))
nb<-strsplit(simulation[1, "nb_v"], "\\|")[[1]]
temp_range<-as.numeric(strsplit(nb[1], "\\,")[[1]])
prec_range<-as.numeric(strsplit(nb[3], "\\,")[[1]])
i=1
for (i in c(1:nrow(example))){
  item<-example[i,]
  if (item$EVO_TYPE==1){
    next()
  }
  if (item$EVO_RATIO==0.05){
    item$EVO_RATIO_LABEL<-"0.1"
  }
  if (item$EVO_RATIO==0.005){
    item$EVO_RATIO_LABEL<-"0.01"
  }
  if (item$EVO_RATIO==1){
    item$EVO_RATIO_LABEL<-"1"
  }
  label<-sprintf("%d_%s_%s_%d_%s", item$SEED_ID, item$DA, item$NB, 
                 item$EVO_TYPE, item$EVO_RATIO_LABEL)
  #df<-readRDS(sprintf("%s/RESULTS/%s/%s_log_nb.rda", base2, label, label))
  #df2<-readRDS(sprintf("%s/RESULTS/%s/%s.log.env.rda", base2, label, label))
  #Format for 2 and 7: 
  #year_i, id, uid, parent_uid, evoType, species->getIDWithParentID().c_str(), nb_str.c_str(), memo.c_str()
  #r, env_range, env_list
  df3<-read.csv(sprintf("%s/RESULTS/%s/%s.nb.log", base2, label, label), head=F, stringsAsFactors = F)
  colnames(df3)<-c("Y", "GLOBAL_ID", "UID", "PARENT_UID", "EVO_TYPE", "SEED_ID", 
                   "ENV_RANGE_1", "ENV_RANGE_1_V1", "ENV_RANGE_1_V2", 
                   "ENV_RANGE_2", "ENV_RANGE_2_V1", "ENV_RANGE_2_V2", 
                   "ENV_RANGE_3", "ENV_RANGE_3_V1", "ENV_RANGE_3_V2", 
                   "SKIP_1",
                   "CHANGE_RATIO",
                   "ENV_1", "ENV_1_V",
                   "ENV_2", "ENV_2_V",
                   "ENV_3", "ENV_3_V",
                   "SKIP_2")
  #head(df)
  #head(df2)
  head(df3)
  df3_item1<-df3%>%dplyr::select(Y, GLOBAL_ID, UID, PARENT_UID, EVO_TYPE, SEED_ID,
                                 ENV_RANGE_1,ENV_RANGE_1_V1, ENV_RANGE_1_V2,
                                 CHANGE_RATIO, ENV_1, ENV_1_V)
  colnames(df3_item1)<-c("Y", "GLOBAL_ID", "UID", "PARENT_UID", "EVO_TYPE", "SEED_ID", 
                         "ENV_RANGE_TYPE", "ENV_RANGE_V1", "ENV_RANGE_V2", 
                         "CHANGE_RATIO",
                         "ENV_TYPE", "ENV_V")
  
  df3_item2<-df3%>%dplyr::select(Y, GLOBAL_ID, UID, PARENT_UID, EVO_TYPE, SEED_ID,
                                 ENV_RANGE_2,ENV_RANGE_2_V1, ENV_RANGE_2_V2,
                                 CHANGE_RATIO, ENV_2, ENV_2_V)
  colnames(df3_item2)<-c("Y", "GLOBAL_ID", "UID", "PARENT_UID", "EVO_TYPE", "SEED_ID", 
                         "ENV_RANGE_TYPE", "ENV_RANGE_V1", "ENV_RANGE_V2", 
                         "CHANGE_RATIO",
                         "ENV_TYPE", "ENV_V")
  
  df3_item3<-df3%>%dplyr::select(Y, GLOBAL_ID, UID, PARENT_UID, EVO_TYPE, SEED_ID,
                                 ENV_RANGE_3,ENV_RANGE_3_V1, ENV_RANGE_3_V2,
                                 CHANGE_RATIO, ENV_3, ENV_3_V)
  colnames(df3_item3)<-c("Y", "GLOBAL_ID", "UID", "PARENT_UID", "EVO_TYPE", "SEED_ID", 
                         "ENV_RANGE_TYPE", "ENV_RANGE_V1", "ENV_RANGE_V2", 
                         "CHANGE_RATIO",
                         "ENV_TYPE", "ENV_V")
  df<-bind_rows(bind_rows(df3_item1, df3_item2), df3_item3)
  df$Y<-df$Y-1200
  df$ENV_RANGE<-df$ENV_RANGE_V2-df$ENV_RANGE_V1
  
  df_i<-df%>%dplyr::filter(ENV_RANGE_TYPE!="Debiased_Minimum_Monthly_Temperature")
  df_i[which(df_i$ENV_RANGE_TYPE=="Debiased_Maximum_Monthly_Precipitation"), "ENV_RANGE_TYPE"]<-"PREC"
  df_i[which(df_i$ENV_RANGE_TYPE=="Debiased_Maximum_Monthly_Temperature"), "ENV_RANGE_TYPE"]<-"TEMP"
  df_sample<-df_i[sample(nrow(df_i), 10000),]
  label<-gsub("0.01", "0.005", label)
  label<-gsub("0.1", "0.05", label)
  saveRDS(df, sprintf("%s/Figures/Niche_Change_Example/%s.rda", base, label))
  
  p<-ggplot(df_sample, aes(x=Y, color=factor(ENV_RANGE_TYPE)))+
    geom_point(aes(y=ENV_RANGE_V1))+
    geom_point(aes(y=ENV_RANGE_V2))+
    geom_hline(yintercept=temp_range)+
    geom_hline(yintercept=prec_range)+
    ggtitle(label)+
    theme_bw()+
    theme(legend.title = element_blank())
  ggsave(p, file=sprintf("%s/Figures/Niche_Change_Example/%s.pdf", base, label))
  cuts<-seq(from=-1200, to=0, by=10)
  df_i$Y_CUT<-Hmisc::cut2(df_i$Y, cuts=cuts)
  p<-ggplot(df_i %>%filter(ENV_RANGE_TYPE=="TEMP"), aes(x=Y_CUT))+
    geom_violin(aes(y=CHANGE_RATIO))+
    ggtitle(label)+
    theme_bw()+
    theme(legend.title = element_blank())
  ggsave(p, file=sprintf("%s/Figures/Niche_Change_Example/CHANGE_RATIO_%s.pdf", base, label),
         width=15, height=5)
}
