library("dplyr")
library("DBI")
library("phytools")
library("tidyr")
library("data.table")
library("tibble")
library("raster")
library("sp")
library("ggplot2")




base<-"/media/huijieqiao/Speciation_Extin/Speciation_Extinction"



#the rda file was generated by global_id_lonlat.r
mask_df<-readRDS(sprintf("%s/Data/ENV/mask_df.rda", base))
colnames(mask_df)[1]<-"GLOBAL_ID"
keycols = c("Y","GLOBAL_ID")
mask_df<-as.data.table(mask_df)
setkeyv(mask_df, keycols)
mydb <- dbConnect(RSQLite::SQLite(), sprintf("%s/Configurations/conf.sqlite", base))  
simulations<-dbReadTable(mydb, "simulations")
dbDisconnect(mydb) 

simulations<-simulations %>% dplyr::filter(evo_type==1)

dim(simulations)
simulations<-simulations[sample(nrow(simulations), nrow(simulations)),]
i=1
for (i in c(1:nrow(simulations))){
  print(paste(i, nrow(simulations)))
  s<-simulations[i,]
  log<-sprintf("%s/Results/%s/%s.log", base, s$label, s$label)
  if (!file.exists(log)){
    print("SKIP 0")
    next()
  }
  target<-sprintf("%s.env.rda", log)
  sp_niche<-NA
  if (file.exists(target)){
    #print("SKIP 1")
    #next()
    ffize<-file.info(target)$size
    print(paste(ffize, target))
    
    
    if (ffize>1000){
      print("SKIP 2")
      next()
    }
    sp_niche<-readRDS(target)
  }
  if (!is.na(sp_niche)){
    print("SKIP 3")
    next()
  }
  saveRDS(NA, target)
  log_df<-read.table(log, head=F, sep=",", stringsAsFactors = F)
  colnames(log_df)<-c("Y", "GLOBAL_ID", "GROUP", "N", "SP_ID", "SUITABLE")
  log_df$SP_ID<-as.character(log_df$SP_ID)
  log_df<-as.data.table(log_df)
  setkeyv(log_df, keycols)
  log_df<-merge(log_df, mask_df, all.x=T, all.y=F)
  log_df<-as_tibble(log_df)
  saveRDS(log_df, target)
  log_df<-NULL
  
  gcinfo(verbose = FALSE) #-- don't show it anymore
  print(gc(TRUE))
}