library(sf)
library(dggridR)
setwd("/media/huijieqiao/Butterfly/Niche_Conservatism/RScript")
grid<-read_sf("../Shape/isea3h8/isea3h8.kml")
area<-st_area(grid)
plot(grid)
dggs<-dggridR::dgconstruct(res = 8)
dggridR::dg_closest_res(dggs, col="spacing_km", val=87)
dgshptogrid(dggs, shpfname = "../Shape/isea3h8/isea3h8_sf.shp")
