library("dplyr")
library("DBI")
library("phytools")
library("tidyr")
library("data.table")
library("tibble")
library("raster")
library("sp")
library("ggplot2")



base<-"/home/huijieqiao/git/ees_3d_data/niche_conservatism"
db_base<-"/home/huijieqiao/git/ees_3d_data/SMART_SPECIES"
base2<-"/media/huijieqiao/Butterfly/SMART_SPECIES"


#the rda file was generated by global_id_lonlat.r
mask_df<-readRDS(sprintf("%s/Data/ENV/mask_df.rda", base))

simulations<-NULL
for (i in c(1,2,7)){
  #for (i in c(7)){
  print(i)
  mydb <- dbConnect(RSQLite::SQLite(), sprintf("%s/conf_%s.sqlite", db_base, i))  
  simulation<-dbReadTable(mydb, "simulations")
  dbDisconnect(mydb) 
  if (is.null(simulations)){
    simulations<-simulation
  }else{
    simulations<-bind_rows(simulation, simulations)
  }
}
handle_label<-function(label){
  if (length(label)==4){
    label<-c(label, label[4])
  }
  label[c(1,4,5)]
}
simulations<-simulations %>% filter(nb!="BROAD")
simulations<-simulations %>% filter(is_run==1)

simulations<-simulations[sample(nrow(simulations), nrow(simulations)),]
for (i in c(1:nrow(simulations))){
  print(paste(i, nrow(simulations)))
  s<-simulations[i,]
  log<-sprintf("%s/RESULTS/%s/%s.log", base2, s$label, s$label)
  target<-sprintf("%s.env.rda", log)
  sp_niche<-NA
  if (file.exists(target)){
    print("SKIP 1")
    next()
    ffize<-file.info(target)$size
    print(paste(ffize, target))
    
    
    if (ffize>1000){
      print("SKIP 2")
      next()
    }
    sp_niche<-readRDS(target)
  }
  if (!is.na(sp_niche)){
    print("SKIP 3")
    next()
  }
  saveRDS(NA, target)
  log_df<-read.table(log, head=F, sep=",", stringsAsFactors = F)
  colnames(log_df)<-c("Y", "ID", "GROUP", "N", "SP_ID", "SUITABLE")
  log_df$SP_ID<-as.character(log_df$SP_ID)
  log_df<-as_tibble(log_df)
  log_df<-left_join(log_df, mask_df, by=c("Y"="Y", "ID"="global_id"))
  saveRDS(log_df, target)
  log_df<-NULL
  
  gcinfo(verbose = FALSE) #-- don't show it anymore
  print(gc(TRUE))
}